# Generated by Django 3.2.6 on 2021-09-04 16:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='logos')),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default.png', null=True, upload_to='user-profile')),
                ('ssn', models.CharField(max_length=9)),
                ('number', models.CharField(max_length=13)),
                ('nation_id', models.CharField(max_length=11)),
                ('specialization', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
